### PR TITLE
feat: upgraded customer.io SDK version to 4.2.0

### PR DESCRIPTION
**Pull request by arnab-p**
**Fixes** # (*issue*)

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:
- [ ] Version upgraded (project, README, gradle, podspec etc)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added unit tests for the code
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by 1abhishekpandey — APPROVED** [review]

**Review by ChryssaAliferi — COMMENTED** [review]
The version needs to be updated in the `Readme.md` file before release. Let me know if this happens automatically from any Github action, if not this needs to be manually changed in this PR, or in a next one.

From:
```
implementation 'com.rudderstack.android.sdk:core:[1.0,2.0)'
implementation 'com.rudderstack.android.integration:customerio:1.0.1'
```
To:
```
implementation 'com.rudderstack.android.sdk:core:[1.0,2.0)'
implementation 'com.rudderstack.android.integration:customerio:1.0.2'
```

To be honest, I would possibly suggest that we go to 1.1.0 as I can see changes in the executable we depend on.

Let me know your thoughts. cc @1abhishekpandey @vgupta98

**Comment by 1abhishekpandey** [comment]
This is not the release PR. As this is of `feat` type PR, the version will be `1.1.0` only.
Regarding the readme.md file changes: We need to manually update that. We can do that while releasing it.

**Comment by ChryssaAliferi** [comment]
> This is not the release PR. As this is of `feat` type PR, the version will be `1.1.0` only, in the release PR. Regarding the readme.md file changes: We need to manually update that. We can do that while releasing it.

I know this is not the release PR, but there is no action that `Readme.md` get's updated from. I am approving this PR, and let's include Read me change in the next PR.

**Review by ChryssaAliferi — APPROVED** [review]

**Comment by 1abhishekpandey** [comment]
Here is the release PR: https://github.com/rudderlabs/rudder-integration-customerio-android/pull/19.
@ChryssaAliferi I've updated the version in the readme file, as mentioned.
I'll close this PR soon.

**Comment by ChryssaAliferi** [comment]
> Here is the release PR: #19. @ChryssaAliferi I've updated the version in the readme file, as mentioned. I'll close this PR soon.

Amazing! Nice one!

**Pull request closed without merging**
